#!/usr/bin/env python3
"""Convert the ZhuangXiuBiKeng source pack into wiki-ready Markdown."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import defaultdict
from datetime import date, datetime, time
from itertools import zip_longest
from pathlib import Path
from typing import Iterable
from urllib.parse import quote

from docx import Document
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "ZhuangXiuBiKeng"
DEFAULT_OUT = SOURCE_ROOT / "wiki-markdown"
MARKER = ".generated-by-convert-zxbk"

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
DOCX_EXTS = {".docx"}
DOC_EXTS = {".doc"}
PDF_EXTS = {".pdf"}
XLSX_EXTS = {".xlsx", ".xlsm", ".xltx", ".xltm"}
XLS_EXTS = {".xls"}
MARKDOWN_EXTS = {".md", ".markdown"}
COPY_ONLY_EXTS = {".dwg"}
SKIP_NAMES = {".DS_Store"}
COMMON_NON_ASCII = set("，。！？、；：“”‘’（）【】《》￥—…㎡²³℃·～＋－×÷％")
XLS_SIGNAL_RE = re.compile(
    r"[，。；：、元㎡]|[0-9]+[、.]|施工|装修|预算|验收|合同|材料|费用|人工|品牌|"
    r"墙|地面|水电|门窗|厨房|卫生间|吊顶|瓷砖|防水|设计|报价|清单|工艺"
)
BIKENG_MANUAL_REL = Path("装修避坑宝典/装修施工工艺标准【一步到位】附赠/避坑手册打印版（100页）.pdf")
BIKENG_MANUAL_MD = Path("装修避坑宝典/装修施工工艺标准【一步到位】附赠/避坑手册打印版（100页）.md")
BIKENG_MANUAL_SPLIT_DIR = BIKENG_MANUAL_MD.with_suffix("")
BIKENG_MANUAL_TOC = [
    (2, "第一节 装修流程计划表", 1),
    (2, "第二节 毛坯房验房记录表", 2),
    (2, "第三节 装修材料", 3),
    (3, "主材明细及选购表", 3),
    (3, "辅材明细及选购表", 8),
    (3, "瓷砖和木地板", 12),
    (3, "瓷砖胶", 17),
    (3, "装修防漏项表", 18),
    (3, "需要提前考虑或购买的材料", 19),
    (2, "第四节 施工工艺注意事项", 21),
    (3, "水电", 21),
    (3, "瓦工", 46),
    (3, "木工", 68),
    (3, "油漆", 73),
    (2, "第五节 全屋定制", 78),
    (3, "装修板材分类与使用", 78),
    (3, "全屋定制", 79),
    (2, "第六节 装修环保", 86),
    (2, "第七节 全屋水电点位布置", 88),
    (2, "第八节 签合同注意事项", 91),
    (2, "第九节 工程验收表", 92),
]


def sha8(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:8]


def md_link(path: Path | str) -> str:
    return quote(Path(path).as_posix(), safe="/#%")


def summary_link(path: Path | str) -> str:
    return Path(path).as_posix()


def wrap_angle(path: Path | str) -> str:
    return f"<{Path(path).as_posix()}>"


def relative_link(target: Path, from_dir: Path) -> Path:
    return Path(os.path.relpath(target, from_dir))


def markdown_internal_href(path: Path | str) -> str:
    return wrap_angle(path)


def safe_filename_stem(name: str) -> str:
    stem = re.sub(r'[\\/:*?"<>|]', "-", name.strip())
    stem = re.sub(r"[()\[\]{}]", "-", stem)
    stem = re.sub(r"\s+", "-", stem)
    stem = re.sub(r"-+", "-", stem).strip("-. ")
    return stem or "untitled"


def clean_text(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d %H:%M")
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, time):
        return value.strftime("%H:%M:%S")
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    text = str(value)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def escape_honkit_templates(text: str) -> str:
    return text.replace("{", "&#123;").replace("}", "&#125;")


def table_cell(value: object) -> str:
    text = clean_text(value)
    text = text.replace("\\", "\\\\")
    text = text.replace("|", "\\|")
    text = text.replace("\n", "<br>")
    return text


def has_content(value: object) -> bool:
    return clean_text(value) != ""


def page_header(title: str, source: Path, kind: str) -> str:
    rel = source.relative_to(SOURCE_ROOT).as_posix()
    return (
        f"# {title}\n\n"
        f"> 来源：`{rel}`  \n"
        f"> 原格式：{kind}\n\n"
    )


def should_skip(path: Path) -> bool:
    if path.name in SKIP_NAMES:
        return True
    if path.name.startswith("~$"):
        return True
    parts = set(path.parts)
    return ".git" in parts or DEFAULT_OUT.name in parts


def discover_sources() -> list[Path]:
    files: list[Path] = []
    for path in SOURCE_ROOT.rglob("*"):
        if path.is_file() and not should_skip(path):
            files.append(path)
    return sorted(files, key=lambda p: p.relative_to(SOURCE_ROOT).as_posix())


def prepare_output_dir() -> Path:
    out_dir = DEFAULT_OUT
    if out_dir.exists():
        if (out_dir / MARKER).exists():
            shutil.rmtree(out_dir)
        else:
            stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            out_dir = SOURCE_ROOT / f"wiki-markdown-{stamp}"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / MARKER).write_text(
        "Generated by scripts/convert_zhuangxiubikeng_to_markdown.py\n",
        encoding="utf-8",
    )
    return out_dir


def build_targets(files: Iterable[Path], out_dir: Path) -> dict[Path, Path]:
    used: set[Path] = set()
    targets: dict[Path, Path] = {}
    for src in files:
        rel = src.relative_to(SOURCE_ROOT)
        parent = out_dir / rel.parent
        stem = safe_filename_stem(src.stem)
        if src.suffix.lower() in MARKDOWN_EXTS and rel.name.lower() == "readme.md":
            stem = "原始README"
        candidate = parent / f"{stem}.md"
        if candidate.relative_to(out_dir) in used:
            candidate = parent / f"{stem}-{src.suffix.lower().lstrip('.')}.md"
        counter = 2
        while candidate.relative_to(out_dir) in used:
            candidate = parent / f"{stem}-{src.suffix.lower().lstrip('.')}-{counter}.md"
            counter += 1
        used.add(candidate.relative_to(out_dir))
        targets[src] = candidate
    return targets


def write_page(out_file: Path, content: str) -> None:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(escape_honkit_templates(content).rstrip() + "\n", encoding="utf-8")


def convert_markdown(src: Path, out_file: Path) -> dict:
    text = src.read_text(encoding="utf-8", errors="replace")
    write_page(out_file, page_header(src.stem, src, "Markdown") + text)
    return {"status": "ok"}


def convert_image(src: Path, out_file: Path) -> dict:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    asset = out_file.parent / f"{safe_filename_stem(src.stem)}{src.suffix.lower()}"
    if asset.exists() and asset.resolve() != src.resolve():
        asset = out_file.parent / f"{src.stem}-{sha8(src.as_posix())}{src.suffix}"
    shutil.copy2(src, asset)

    details = ""
    try:
        with Image.open(asset) as img:
            details = f"\n\n图片尺寸：{img.width} x {img.height}\n"
    except Exception:
        details = ""

    rel_asset = asset.relative_to(out_file.parent)
    body = (
        page_header(src.stem, src, src.suffix.lower().lstrip(".").upper())
        + f"![{src.stem}]({wrap_angle(rel_asset)})"
        + details
    )
    write_page(out_file, body)
    return {"status": "ok", "asset": asset.name}


def fallback_docx(src: Path) -> str:
    doc = Document(str(src))
    parts: list[str] = []
    for para in doc.paragraphs:
        text = clean_text(para.text)
        if text:
            parts.append(text)
    for table in doc.tables:
        rows: list[list[str]] = []
        for row in table.rows:
            rows.append([table_cell(cell.text) for cell in row.cells])
        parts.append(markdown_table(rows))
    return "\n\n".join(part for part in parts if part.strip())


def convert_docx(src: Path, out_file: Path) -> dict:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    asset_dir = f"assets_{sha8(src.relative_to(SOURCE_ROOT).as_posix())}"
    result = subprocess.run(
        [
            "pandoc",
            str(src),
            "-f",
            "docx",
            "-t",
            "gfm",
            "--wrap=none",
            f"--extract-media={asset_dir}",
            "-o",
            out_file.name,
        ],
        cwd=out_file.parent,
        capture_output=True,
        text=True,
        timeout=240,
    )
    if result.returncode == 0:
        body = out_file.read_text(encoding="utf-8", errors="replace")
        write_page(out_file, page_header(src.stem, src, "DOCX") + body)
        return {"status": "ok", "method": "pandoc"}

    body = fallback_docx(src)
    write_page(
        out_file,
        page_header(src.stem, src, "DOCX")
        + body
        + "\n\n> 注：Pandoc 转换失败，已用 Word 文本/表格提取方式兜底。\n",
    )
    return {"status": "ok", "method": "python-docx", "warning": result.stderr.strip()}


def convert_doc(src: Path, out_file: Path) -> dict:
    html = subprocess.run(
        ["textutil", "-convert", "html", "-stdout", str(src)],
        capture_output=True,
        timeout=180,
    )
    if html.returncode == 0 and html.stdout.strip():
        pandoc = subprocess.run(
            ["pandoc", "-f", "html", "-t", "gfm", "--wrap=none"],
            input=html.stdout,
            capture_output=True,
            timeout=180,
        )
        if pandoc.returncode == 0 and pandoc.stdout.strip():
            body = pandoc.stdout.decode("utf-8", errors="replace")
            write_page(out_file, page_header(src.stem, src, "DOC") + body)
            return {"status": "ok", "method": "textutil+pandoc"}

    txt = subprocess.run(
        ["textutil", "-convert", "txt", "-stdout", str(src)],
        capture_output=True,
        timeout=180,
    )
    if txt.returncode == 0 and txt.stdout.strip():
        body = txt.stdout.decode("utf-8", errors="replace")
        write_page(out_file, page_header(src.stem, src, "DOC") + body)
        return {"status": "ok", "method": "textutil"}

    raise RuntimeError((txt.stderr or html.stderr).decode("utf-8", errors="replace"))


def pdf_page_markdown(text: str) -> str:
    pages = text.replace("\r", "").split("\f")
    parts: list[str] = []
    for index, page in enumerate(pages, start=1):
        lines = [line.rstrip() for line in page.splitlines()]
        while lines and not lines[0].strip():
            lines.pop(0)
        while lines and not lines[-1].strip():
            lines.pop()
        if not lines:
            continue
        rendered = "\n".join((line + "  ") if line.strip() else "" for line in lines)
        parts.append(f"## 第 {index} 页\n\n{rendered}")
    return "\n\n".join(parts)


def render_pdf_pages_from_file(
    pdf_file: Path,
    out_file: Path,
    asset_key: str,
    *,
    dpi: int = 180,
) -> tuple[Path, list[Path]]:
    asset_dir = out_file.parent / f"assets_{sha8(asset_key)}" / "pdf-pages"
    asset_dir.mkdir(parents=True, exist_ok=True)
    prefix = asset_dir / "page"
    result = subprocess.run(
        ["pdftoppm", "-jpeg", "-r", str(dpi), str(pdf_file), str(prefix)],
        capture_output=True,
        text=True,
        timeout=600,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "pdftoppm failed")
    pages = sorted(asset_dir.glob("page-*.jpg"), key=lambda p: p.name)
    return asset_dir, pages


def render_pdf_pages(src: Path, out_file: Path) -> tuple[Path, list[Path]]:
    return render_pdf_pages_from_file(
        src,
        out_file,
        src.relative_to(SOURCE_ROOT).as_posix(),
    )


def crop_image_whitespace(image_file: Path, *, padding: int = 36, threshold: int = 245) -> None:
    with Image.open(image_file) as image:
        rgb = image.convert("RGB")
        gray = rgb.convert("L")
        mask = gray.point(lambda pixel: 255 if pixel < threshold else 0, "1")
        bbox = mask.getbbox()
        if not bbox:
            return

        left, top, right, bottom = bbox
        left = max(0, left - padding)
        top = max(0, top - padding)
        right = min(rgb.width, right + padding)
        bottom = min(rgb.height, bottom + padding)

        if (left, top, right, bottom) == (0, 0, rgb.width, rgb.height):
            return
        rgb.crop((left, top, right, bottom)).save(image_file, quality=92, optimize=True)


def crop_pdf_page_whitespace(page_images: Iterable[Path]) -> None:
    for image in page_images:
        crop_image_whitespace(image)


def crop_image_to_table_grid(image_file: Path, *, padding: int = 18, threshold: int = 235) -> None:
    with Image.open(image_file) as image:
        gray = image.convert("L")
        width, height = gray.size
        pixels = gray.load()

        column_counts = []
        for x in range(width):
            count = 0
            for y in range(height):
                if pixels[x, y] < threshold:
                    count += 1
            column_counts.append(count)

        row_counts = []
        for y in range(height):
            count = 0
            for x in range(width):
                if pixels[x, y] < threshold:
                    count += 1
            row_counts.append(count)

        table_columns = [x for x, count in enumerate(column_counts) if count > height * 0.15]
        table_rows = [y for y, count in enumerate(row_counts) if count > width * 0.25]
        if not table_columns or not table_rows:
            return

        left = max(0, min(table_columns) - padding)
        right = min(width, max(table_columns) + padding)
        top = max(0, min(table_rows) - padding)
        bottom = min(height, max(table_rows) + padding)
        if right - left < width * 0.25 or bottom - top < height * 0.25:
            return

        image.convert("RGB").crop((left, top, right, bottom)).save(
            image_file,
            quality=92,
            optimize=True,
        )


def crop_flow_sheet_images(page_images: Iterable[Path]) -> None:
    for image in page_images:
        crop_image_whitespace(image)
        crop_image_to_table_grid(image)


def page_span(start: int, end: int) -> str:
    return f"手册第 {start} 页" if start == end else f"手册第 {start}-{end} 页"


def toc_entry_has_children(index: int) -> bool:
    level = BIKENG_MANUAL_TOC[index][0]
    for next_level, _, _ in BIKENG_MANUAL_TOC[index + 1 :]:
        if next_level <= level:
            return False
        return True
    return False


def toc_entry_end(index: int, max_manual_page: int, children: bool) -> int:
    level, _, start = BIKENG_MANUAL_TOC[index]
    for next_level, _, next_start in BIKENG_MANUAL_TOC[index + 1 :]:
        if next_start <= start:
            continue
        if children and next_level <= level:
            return next_start - 1
        if not children:
            return next_start - 1
    return max_manual_page


def honkit_anchor(text: str) -> str:
    anchor = text.strip().lower()
    anchor = re.sub(r"\s+", "-", anchor)
    anchor = re.sub(r"[^\w\u4e00-\u9fff\-（）()]+", "", anchor)
    return anchor


def manual_heading_text(index: int, max_manual_page: int) -> str:
    _, title, start = BIKENG_MANUAL_TOC[index]
    end = toc_entry_end(index, max_manual_page, toc_entry_has_children(index))
    return f"{title}（{page_span(start, end)}）"


def manual_page_rel(index: int) -> Path:
    _, title, start = BIKENG_MANUAL_TOC[index]
    return BIKENG_MANUAL_SPLIT_DIR / f"{start:02d}-{safe_filename_stem(title)}.md"


def manual_summary_lines(path_prefix: Path = Path("."), indent: int = 0) -> list[str]:
    max_manual_page = 98
    manual_path = path_prefix / BIKENG_MANUAL_MD
    lines = [f"{'    ' * indent}* [装修避坑手册打印（100页）]({summary_link(manual_path)})"]
    for index, (level, title, _) in enumerate(BIKENG_MANUAL_TOC):
        page_path = path_prefix / manual_page_rel(index)
        child_indent = indent + level - 1
        lines.append(f"{'    ' * child_indent}* [{title}]({summary_link(page_path)})")
    return lines


def pdf_page_image_line(page_images: list[Path], out_file: Path, pdf_page: int, alt: str) -> str:
    if pdf_page < 1 or pdf_page > len(page_images):
        return f"> 缺少 PDF 第 {pdf_page} 页图片。"
    rel_image = relative_link(page_images[pdf_page - 1], out_file.parent)
    return f"![{alt}]({wrap_angle(rel_image)})"


def child_toc_indexes(index: int) -> list[int]:
    level = BIKENG_MANUAL_TOC[index][0]
    children: list[int] = []
    for child_index, (child_level, _, _) in enumerate(BIKENG_MANUAL_TOC[index + 1 :], start=index + 1):
        if child_level <= level:
            break
        if child_level == level + 1:
            children.append(child_index)
    return children


def convert_bikeng_manual_pdf(src: Path, out_file: Path, original_pdf: Path, page_images: list[Path]) -> dict:
    max_manual_page = max(len(page_images) - 2, 0)
    split_dir = out_file.parent / BIKENG_MANUAL_SPLIT_DIR.name
    split_dir.mkdir(parents=True, exist_ok=True)
    pdf_link = f"[打开原始 PDF]({md_link(original_pdf.relative_to(out_file.parent))})"
    lines = [
        page_header(src.stem, src, "PDF"),
        f"> {pdf_link}",
        "",
        "这个入口页只放目录，具体页面图片已经拆到下面每个章节页面，避免打开时一次加载 100 页图片。",
        "",
        "## 原 PDF",
        "",
        f"- {pdf_link}",
        "",
        "## 目录",
        "",
    ]
    for index, (level, title, _) in enumerate(BIKENG_MANUAL_TOC):
        indent = "  " * (level - 2)
        rel_page = manual_page_rel(index).relative_to(BIKENG_MANUAL_MD.parent)
        lines.append(
            f"{indent}- [{manual_heading_text(index, max_manual_page)}]({markdown_internal_href(rel_page)})"
        )
    write_page(out_file, "\n".join(lines))

    for index, (level, title, start) in enumerate(BIKENG_MANUAL_TOC):
        has_children = toc_entry_has_children(index)
        end = toc_entry_end(index, max_manual_page, has_children)
        page_path = out_file.parent / manual_page_rel(index).relative_to(BIKENG_MANUAL_MD.parent)
        child_lines = [
            f"# {manual_heading_text(index, max_manual_page)}",
            "",
            f"[返回目录]({markdown_internal_href(Path('..') / BIKENG_MANUAL_MD.name)})",
            "",
            f"> [打开原始 PDF]({md_link(relative_link(original_pdf, page_path.parent))})",
            "",
        ]
        children = child_toc_indexes(index)
        if children:
            child_lines.extend(["## 子目录", ""])
            for child_index in children:
                child_lines.append(
                    f"- [{manual_heading_text(child_index, max_manual_page)}]"
                    f"({markdown_internal_href(manual_page_rel(child_index).name)})"
                )
            child_lines.append("")
        else:
            for manual_page in range(start, end + 1):
                pdf_page = manual_page + 2
                child_lines.append(
                    pdf_page_image_line(
                        page_images,
                        page_path,
                        pdf_page,
                        title,
                    )
                )
                child_lines.append("")
        write_page(page_path, "\n".join(child_lines))

    return {
        "status": "ok",
        "method": "pdftoppm+manual-toc-split-pages",
        "pages": len(page_images),
        "split_pages": len(BIKENG_MANUAL_TOC),
    }


def convert_pdf(src: Path, out_file: Path) -> dict:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    original_pdf = out_file.parent / f"{safe_filename_stem(src.stem)}.pdf"
    if original_pdf.exists() and original_pdf.resolve() != src.resolve():
        original_pdf = out_file.parent / f"{safe_filename_stem(src.stem)}-{sha8(src.as_posix())}.pdf"
    shutil.copy2(src, original_pdf)

    result = subprocess.run(
        ["pdftotext", "-layout", "-enc", "UTF-8", str(src), "-"],
        capture_output=True,
        timeout=420,
    )
    text = result.stdout.decode("utf-8", errors="replace") if result.stdout else ""
    text_body = pdf_page_markdown(text)
    try:
        _, page_images = render_pdf_pages(src, out_file)
    except Exception as exc:
        page_images = []
        render_warning = str(exc)
    else:
        render_warning = ""

    if src.relative_to(SOURCE_ROOT) == BIKENG_MANUAL_REL and page_images:
        return convert_bikeng_manual_pdf(src, out_file, original_pdf, page_images)

    image_body = []
    for index, image in enumerate(page_images, start=1):
        rel_image = image.relative_to(out_file.parent)
        image_body.append(f"![{src.stem}]({wrap_angle(rel_image)})")

    pdf_link = f"[打开原始 PDF]({md_link(original_pdf.relative_to(out_file.parent))})"
    body_parts = [f"> {pdf_link}\n"]
    if image_body:
        body_parts.extend(image_body)
    elif render_warning:
        body_parts.append(f"> PDF 页面图片渲染失败：{render_warning}\n")

    if text_body.strip():
        body_parts.extend(["## 可复制文字", text_body])
        status = {"status": "ok", "method": "pdftotext+pdftoppm", "pages": len(page_images)}
    else:
        status = {
            "status": "ok" if page_images else "partial",
            "method": "pdftoppm",
            "pages": len(page_images),
            "warning": "no text extracted",
        }
        if not page_images:
            body_parts.append("> 这个 PDF 未提取到可复制文字，可能是扫描图或图片型 PDF。")
    write_page(out_file, page_header(src.stem, src, "PDF") + "\n\n".join(body_parts))
    return status


def markdown_table(rows: list[list[object]]) -> str:
    if not rows:
        return ""
    width = max((len(row) for row in rows), default=0)
    if width == 0:
        return ""
    headers = [get_column_letter(i + 1) for i in range(width)]
    lines = [
        "| " + " | ".join(table_cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        padded = list(row) + [""] * (width - len(row))
        lines.append("| " + " | ".join(table_cell(cell) for cell in padded) + " |")
    return "\n".join(lines)


def xlsx_pdf_cell_text(value: object) -> str:
    text = clean_text(value)
    text = text.replace("<br>", "\n")
    return text


def xlsx_col_widths(rows: list[list[object]], max_width: float = 2200) -> list[float]:
    if not rows:
        return []
    width = max(len(row) for row in rows)
    widths: list[float] = []
    for col_index in range(width):
        samples = [
            xlsx_pdf_cell_text(row[col_index])
            for row in rows
            if col_index < len(row) and has_content(row[col_index])
        ]
        if not samples:
            widths.append(44)
            continue
        max_line = 0
        avg_line = 0
        for sample in samples[:80]:
            lines = sample.splitlines() or [sample]
            max_line = max(max_line, *(len(line) for line in lines))
            avg_line += max(len(line) for line in lines)
        avg_line = avg_line / max(min(len(samples), 80), 1)
        estimated = max(48, min(220, max_line * 4.2, avg_line * 5.8))
        widths.append(estimated)

    total = sum(widths)
    if total > max_width and total > 0:
        ratio = max_width / total
        widths = [max(36, width * ratio) for width in widths]
    return widths


def build_xlsx_pdf(src: Path, pdf_file: Path) -> int:
    from xml.sax.saxutils import escape as xml_escape

    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.cidfonts import UnicodeCIDFont
    from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    try:
        pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
    except Exception:
        pass

    values_wb = load_workbook(src, read_only=True, data_only=True)
    formula_wb = load_workbook(src, read_only=True, data_only=False)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "XlsxSheetTitle",
        parent=styles["Heading1"],
        fontName="STSong-Light",
        fontSize=18,
        leading=22,
        spaceAfter=12,
    )
    cell_style = ParagraphStyle(
        "XlsxCell",
        parent=styles["BodyText"],
        fontName="STSong-Light",
        fontSize=7.5,
        leading=9.5,
        wordWrap="CJK",
    )
    header_style = ParagraphStyle(
        "XlsxHeaderCell",
        parent=cell_style,
        fontName="STSong-Light",
        fontSize=8,
        leading=10,
    )

    sheet_rows: list[tuple[str, list[list[object]]]] = []
    for sheet_name in values_wb.sheetnames:
        value_ws = values_wb[sheet_name]
        formula_ws = formula_wb[sheet_name]
        rows = iter_sheet_rows(value_ws, formula_ws)
        if rows:
            sheet_rows.append((sheet_name, rows))
    values_wb.close()
    formula_wb.close()

    max_table_width = 2200
    page_width = 900
    for _, rows in sheet_rows:
        widths = xlsx_col_widths(rows, max_table_width)
        if widths:
            page_width = max(page_width, min(max_table_width + 72, sum(widths) + 72))

    story = []
    for sheet_index, (sheet_name, rows) in enumerate(sheet_rows):
        if sheet_index:
            story.append(PageBreak())
        story.append(Paragraph(xml_escape(sheet_name), title_style))
        story.append(Spacer(1, 6))
        widths = xlsx_col_widths(rows, max_table_width)
        data = []
        for row_index, row in enumerate(rows):
            padded = list(row) + [""] * (len(widths) - len(row))
            style = header_style if row_index == 0 else cell_style
            data.append(
                [
                    Paragraph(
                        xml_escape(xlsx_pdf_cell_text(cell)).replace("\n", "<br/>"),
                        style,
                    )
                    for cell in padded[: len(widths)]
                ]
            )
        table = Table(data, colWidths=widths, repeatRows=1 if len(data) > 1 else 0)
        table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#c8c8c8")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 3),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f2f2")),
                ]
            )
        )
        story.append(table)

    if not story:
        story.append(Paragraph("未提取到可转换的表格内容。", cell_style))

    pdf_file.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(pdf_file),
        pagesize=(page_width, 2200),
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36,
    )
    doc.build(story)
    return len(sheet_rows)


def iter_sheet_rows(value_ws, formula_ws) -> list[list[object]]:
    rows: list[list[object]] = []
    used_cols: set[int] = set()
    for value_row, formula_row in zip_longest(
        value_ws.iter_rows(values_only=True),
        formula_ws.iter_rows(values_only=True),
        fillvalue=(),
    ):
        value_row = value_row or ()
        formula_row = formula_row or ()
        width = max(len(value_row), len(formula_row))
        row_values: list[object] = []
        row_has_content = False
        for col_index in range(width):
            value = value_row[col_index] if col_index < len(value_row) else None
            formula = formula_row[col_index] if col_index < len(formula_row) else None
            chosen = value
            if not has_content(chosen) and isinstance(formula, str) and formula.startswith("="):
                chosen = formula
            row_values.append(chosen)
            if has_content(chosen):
                row_has_content = True
                used_cols.add(col_index)
        if row_has_content:
            rows.append(row_values)

    if not rows or not used_cols:
        return []
    min_col = min(used_cols)
    max_col = max(used_cols)
    return [row[min_col : max_col + 1] for row in rows]


def convert_xlsx(src: Path, out_file: Path) -> dict:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    pdf_file = out_file.parent / f"{safe_filename_stem(src.stem)}.pdf"
    if pdf_file.exists() and pdf_file.resolve() != src.resolve():
        pdf_file = out_file.parent / f"{safe_filename_stem(src.stem)}-{sha8(src.as_posix())}.pdf"

    converted_sheets = build_xlsx_pdf(src, pdf_file)
    rel_src = src.relative_to(SOURCE_ROOT).as_posix()
    enlarge_flow_sheet = rel_src.startswith("装修避坑宝典/51天装修流程表/")
    _, page_images = render_pdf_pages_from_file(
        pdf_file,
        out_file,
        rel_src,
        dpi=240 if enlarge_flow_sheet else 160,
    )
    if enlarge_flow_sheet:
        crop_flow_sheet_images(page_images)
    pdf_link = f"[打开 PDF]({md_link(pdf_file.relative_to(out_file.parent))})"
    parts = [page_header(src.stem, src, src.suffix.lower().lstrip(".").upper()), f"> {pdf_link}", ""]
    if page_images:
        for image in page_images:
            rel_image = image.relative_to(out_file.parent)
            parts.append(f"![{src.stem}]({wrap_angle(rel_image)})")
            parts.append("")
    else:
        parts.append("> 未渲染出图片。")
    write_page(out_file, "\n".join(parts))
    return {
        "status": "ok" if page_images else "partial",
        "method": "xlsx-to-pdf-to-images",
        "sheets": converted_sheets,
        "pages": len(page_images),
    }


def printable_ratio(text: str) -> float:
    if not text:
        return 0.0
    good = sum(1 for ch in text if ch.isprintable() and not ch.isspace())
    return good / max(len(text), 1)


def looks_like_human_text(text: str) -> bool:
    stripped = text.strip()
    if len(stripped) < 2:
        return False
    bad = 0
    signal = 0
    for ch in stripped:
        if ch.isspace():
            continue
        if "\u4e00" <= ch <= "\u9fff":
            signal += 1
            continue
        if ch.isascii() and ch.isprintable():
            if ch.isalnum():
                signal += 1
            continue
        if "\uff00" <= ch <= "\uffef" or ch in COMMON_NON_ASCII:
            signal += 1
            continue
        bad += 1
    if signal < 2:
        return False
    return bad / max(len(stripped), 1) <= 0.12


def is_binary_allowed_char(ch: str) -> bool:
    return (
        "\u4e00" <= ch <= "\u9fff"
        or (ch.isascii() and ch.isprintable())
        or "\uff00" <= ch <= "\uffef"
        or ch in COMMON_NON_ASCII
        or ch.isspace()
    )


def binary_chunk_score(text: str) -> int:
    score = len(re.findall(r"[\u4e00-\u9fff]", text))
    score += 8 * len(XLS_SIGNAL_RE.findall(text))
    score -= sum(1 for ch in text if not is_binary_allowed_char(ch))
    return score


def normalize_binary_chunk(chunk: str) -> str:
    parts = [part.strip() for part in re.split(r"[Ā\x00]+", chunk) if part.strip()]
    if parts:
        chunk = max(parts, key=binary_chunk_score)
    chunk = re.sub(r"\s+", " ", chunk).strip()
    chunk = re.sub(r"^[^\u4e00-\u9fffA-Za-z0-9￥（【《]+", "", chunk)
    return chunk


def extract_binary_strings(src: Path) -> list[str]:
    data = src.read_bytes()
    candidates: list[str] = []
    for encoding in ("utf-16le", "gb18030", "utf-8"):
        decoded = data.decode(encoding, errors="ignore")
        if printable_ratio(decoded) < 0.02:
            continue
        chunks = re.split(r"[\x00-\x08\x0b\x0c\x0e-\x1f]+", decoded)
        for chunk in chunks:
            chunk = normalize_binary_chunk(chunk)
            if len(chunk) < 4:
                continue
            if not looks_like_human_text(chunk):
                continue
            has_signal = re.search(r"[\u4e00-\u9fffA-Za-z0-9]", chunk)
            if not has_signal:
                continue
            if not XLS_SIGNAL_RE.search(chunk):
                continue
            if len(chunk) > 240:
                chunk = chunk[:240].rstrip() + "..."
            candidates.append(chunk)

    seen: set[str] = set()
    cleaned: list[str] = []
    noise = {"Root Entry", "Workbook", "SummaryInformation", "DocumentSummaryInformation"}
    for item in candidates:
        if item in seen or item in noise:
            continue
        if item.startswith("_") and len(item) < 8:
            continue
        seen.add(item)
        cleaned.append(item)
        if len(cleaned) >= 240:
            break
    return cleaned


def convert_xls(src: Path, out_file: Path) -> dict:
    strings = extract_binary_strings(src)
    body = page_header(src.stem, src, "XLS")
    body += (
        "> 这是旧版 Excel 二进制文件，当前环境没有可靠的旧版表格解析器；"
        "下面是从文件中提取出的可读文本片段，表格结构可能不完整。\n\n"
    )
    if strings:
        body += "\n".join(f"- {item}" for item in strings)
        status = {"status": "partial", "method": "binary-string-extract", "items": len(strings)}
    else:
        body += "> 未提取到可读文本。\n"
        status = {"status": "partial", "method": "binary-string-extract", "items": 0}
    write_page(out_file, body)
    return status


def convert_copy_only(src: Path, out_file: Path) -> dict:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    asset = out_file.parent / f"{safe_filename_stem(src.stem)}{src.suffix.lower()}"
    shutil.copy2(src, asset)
    body = (
        page_header(src.stem, src, src.suffix.lower().lstrip(".").upper())
        + f"这个文件不是文本类资料，已复制为附件：[{src.name}]({md_link(asset.relative_to(out_file.parent))})\n"
    )
    write_page(out_file, body)
    return {"status": "partial", "method": "copy-attachment"}


def convert_file(src: Path, out_file: Path) -> dict:
    ext = src.suffix.lower()
    if ext in MARKDOWN_EXTS:
        return convert_markdown(src, out_file)
    if ext in DOCX_EXTS:
        return convert_docx(src, out_file)
    if ext in DOC_EXTS:
        return convert_doc(src, out_file)
    if ext in PDF_EXTS:
        return convert_pdf(src, out_file)
    if ext in XLSX_EXTS:
        return convert_xlsx(src, out_file)
    if ext in XLS_EXTS:
        return convert_xls(src, out_file)
    if ext in IMAGE_EXTS:
        return convert_image(src, out_file)
    if ext in COPY_ONLY_EXTS:
        return convert_copy_only(src, out_file)
    raise RuntimeError(f"Unsupported file type: {ext}")


def make_dir_indexes(out_dir: Path, records: list[dict]) -> None:
    pages_by_dir: dict[Path, list[dict]] = defaultdict(list)
    dirs: set[Path] = {Path(".")}
    for record in records:
        rel_page = Path(record["markdown"])
        pages_by_dir[rel_page.parent].append(record)
        current = rel_page.parent
        while current != Path("."):
            dirs.add(current)
            current = current.parent
    for directory in sorted(dirs, key=lambda p: (len(p.parts), p.as_posix())):
        if directory == Path("."):
            continue
        parent = out_dir / directory
        parent.mkdir(parents=True, exist_ok=True)
        child_dirs = sorted(
            [
                d
                for d in dirs
                if d.parent == directory and d != directory and d != BIKENG_MANUAL_SPLIT_DIR
            ],
            key=lambda p: p.name,
        )
        pages = sorted(pages_by_dir.get(directory, []), key=lambda r: r["title"])
        title = directory.name
        lines = [f"# {title}", "", f"[返回上一级]({md_link(Path('..') / 'README.md')})", ""]
        if child_dirs:
            lines.extend(["## 子目录", ""])
            for child in child_dirs:
                lines.append(f"- [{child.name}]({md_link(Path(child.name) / 'README.md')})")
            lines.append("")
        if pages:
            lines.extend(["## 文件", ""])
            for page in pages:
                link = Path(page["markdown"]).name
                lines.append(f"- [{page['title']}]({md_link(link)})")
            lines.append("")
        write_page(parent / "README.md", "\n".join(lines))


def make_root_indexes(out_dir: Path, records: list[dict], errors: list[dict]) -> None:
    ok_count = sum(1 for r in records if r["status"] == "ok")
    partial_count = sum(1 for r in records if r["status"] == "partial")

    root_children = sorted({Path(r["markdown"]).parts[0] for r in records if Path(r["markdown"]).parts})
    lines = [
        "# 装修避坑宝典 Markdown 版",
        "",
        "这份目录由 `ZhuangXiuBiKeng` 原始资料转换而来，适合复制到 wiki 或作为 HonKit/GitBook 内容使用。",
        "",
        "## 转换概况",
        "",
        f"- Markdown 页面：{len(records)}",
        f"- 完整提取：{ok_count}",
        f"- 部分提取/附件页：{partial_count}",
        f"- 转换失败：{len(errors)}",
        "",
        "## 使用说明",
        "",
        "- Word、Excel 已尽量转为正文或 Markdown 表格。",
        "- PDF 已渲染为图片，并保留可复制文字和原始 PDF 附件。",
        "- 图片已复制到对应目录并生成引用页。",
        "- 旧版 `.xls` 因格式限制，输出为可读文本片段，表格结构可能不完整。",
        "",
        "## 目录",
        "",
    ]
    if (out_dir / BIKENG_MANUAL_MD).exists():
        lines.extend(
            [
                "## 常用入口",
                "",
                f"- [装修避坑手册打印（100页）]({md_link(BIKENG_MANUAL_MD)})",
                "",
                "## 完整目录",
                "",
            ]
        )
    for child in root_children:
        if (out_dir / child / "README.md").exists():
            lines.append(f"- [{child}]({md_link(Path(child) / 'README.md')})")

    if errors:
        lines.extend(["", "## 转换失败文件", ""])
        for item in errors:
            lines.append(f"- `{item['source']}`：{item['error']}")

    write_page(out_dir / "README.md", "\n".join(lines))

    summary = ["# Summary", "", "* [首页](README.md)"]
    if (out_dir / BIKENG_MANUAL_MD).exists():
        summary.extend(manual_summary_lines())

    def add_dir(directory: Path, indent: int = 1) -> None:
        children = sorted(
            [
                p
                for p in (out_dir / directory).iterdir()
                if p.is_dir()
                and not p.name.startswith("assets_")
                and p.name != "media"
                and p.relative_to(out_dir) != BIKENG_MANUAL_SPLIT_DIR
            ],
            key=lambda p: p.name,
        )
        pages = sorted(
            [
                p
                for p in (out_dir / directory).glob("*.md")
                if p.name not in {"README.md", "SUMMARY.md", "转换报告.md", "原始README.md"}
                and p.relative_to(out_dir) != BIKENG_MANUAL_MD
            ],
            key=lambda p: p.stem,
        )
        prefix = "    " * indent
        for child in children:
            rel = child.relative_to(out_dir)
            summary.append(f"{prefix}* [{child.name}]({summary_link(rel / 'README.md')})")
            add_dir(rel, indent + 1)
        for page in pages:
            rel = page.relative_to(out_dir)
            summary.append(f"{prefix}* [{page.stem}]({summary_link(rel)})")

    add_dir(Path("."), 0)
    write_page(out_dir / "SUMMARY.md", "\n".join(summary))

    report = {
        "source_root": str(SOURCE_ROOT),
        "output_root": str(out_dir),
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "records": records,
        "errors": errors,
    }
    (out_dir / "conversion-report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    report_lines = [
        "# 转换报告",
        "",
        f"- 输出目录：`{out_dir}`",
        f"- Markdown 页面：{len(records)}",
        f"- 转换失败：{len(errors)}",
        "",
        "## 部分提取说明",
        "",
    ]
    partial = [r for r in records if r["status"] == "partial"]
    if partial:
        for item in partial:
            report_lines.append(f"- `{item['source']}`：{item.get('method', 'partial')}")
    else:
        report_lines.append("- 无")
    if errors:
        report_lines.extend(["", "## 失败文件", ""])
        for item in errors:
            report_lines.append(f"- `{item['source']}`：{item['error']}")
    write_page(out_dir / "转换报告.md", "\n".join(report_lines))


def main() -> int:
    if not SOURCE_ROOT.exists():
        print(f"Missing source directory: {SOURCE_ROOT}", file=sys.stderr)
        return 1
    out_dir = prepare_output_dir()
    files = discover_sources()
    targets = build_targets(files, out_dir)
    records: list[dict] = []
    errors: list[dict] = []

    for index, src in enumerate(files, start=1):
        rel_source = src.relative_to(SOURCE_ROOT).as_posix()
        out_file = targets[src]
        rel_markdown = out_file.relative_to(out_dir).as_posix()
        try:
            result = convert_file(src, out_file)
            record = {
                "source": rel_source,
                "markdown": rel_markdown,
                "title": src.stem,
                "status": result.get("status", "ok"),
                **{k: v for k, v in result.items() if k != "status"},
            }
            records.append(record)
            print(f"[{index}/{len(files)}] ok {rel_source}")
        except Exception as exc:  # Keep the batch going; report failures in the wiki.
            errors.append({"source": rel_source, "error": str(exc)})
            print(f"[{index}/{len(files)}] fail {rel_source}: {exc}", file=sys.stderr)

    make_dir_indexes(out_dir, records)
    make_root_indexes(out_dir, records, errors)
    print(f"Generated {len(records)} markdown pages in {out_dir}")
    if errors:
        print(f"{len(errors)} files failed; see 转换报告.md", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
